name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Coverlet coverage test
      uses: b3b00/coverlet-action@1.2.2
      with:
        output: 'lcov.info'
        outputFormat: 'json'
        testProject: 'Flax.Tests/Flax.Tests.csproj'
      
      
